#!/usr/bin/env python3
"""Script for Tkinter GUI chat client."""
from socket import AF_INET, socket, SOCK_STREAM
from threading import Thread
import tkinter

def receive():
    """Handles receiving of messages."""
    while True:
        try:
            msg = client_socket.recv(BUFSIZ).decode("utf8")
            msg_list.insert(tkinter.END, msg)
        except OSError:  # Possibly client has left the chat.
            break


def send(event=None):  # event is passed by binders.
    """Handles sending of messages."""
    msg = my_msg.get()
    my_msg.set("")  # Clears input field.
    client_socket.send(bytes(msg, "utf8"))
    if msg == "{quit}":
        client_socket.close()
        top.quit()


def on_closing(event=None):
    """This function is to be called when the window is closed."""
    msg_list.set("{quit}")
    send()


top = tkinter.Tk()
top.title("ChApp")
top.geometry("1000x615")

filename = tkinter.PhotoImage(file="C:\\Users\\Ayushee\\Documents\\PBLimage1.png")
background_label = tkinter.Label(top, image=filename)
background_label.place(x=0, y=0, relwidth=1, relheight=1)

frame = tkinter.Frame(top)

my_msg = tkinter.StringVar()  # For the messages to be sent.
my_msg.set("Type your messages here!")
scrollbar = tkinter.Scrollbar(frame, bg="#251f36")  # To navigate through past messages.
# Following will contain the messages.
msg_list = tkinter.Listbox(frame, height=30, width=65, yscrollcommand=scrollbar.set, bg="#251f36", fg="white")
scrollbar.pack(side=tkinter.RIGHT, fill=tkinter.Y)
msg_list.pack(side=tkinter.LEFT, fill=tkinter.BOTH)
msg_list.pack()
frame.pack()

entry_field = tkinter.Entry(top, textvariable=my_msg)
entry_field.bind("<Return>", send)
entry_field.pack(ipadx = 20, ipady = 10)
send_button = tkinter.Button(top, text="SEND", command=send)
send_button.pack()


# ----Now comes the sockets part----

HOST = '10.100.0.67'
PORT = 12346
if not PORT:
    PORT = 33000
else:
    PORT = int(PORT)

BUFSIZ = 1024
ADDR = (HOST, PORT)

client_socket = socket(AF_INET, SOCK_STREAM)
client_socket.connect(ADDR)
receive_thread = Thread(target=receive)
receive_thread.start()
tkinter.mainloop()  # Starts GUI execution.
